#sdk: /Users/alexb/.rvm/gems/ruby-1.9.3-p327/gems/rhodes-3.5.1.12
sdkversion: 4.0.0
# sdkversion: 3.5.1.12
name: ffcrm-client
version: 1.01
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.1
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.ffcrm-client
  BundleURLScheme: ffcrm-client
wp:
  productid: 3a5cd080-d2a9-012f-5f83-482a1416020c
symbian:
  uid: '0xe7a6aba2'

android:
  version: 2.1
  # version: 4.1.2
  # version: 3.2

#capabilities: ["vibrate"]

extensions: ["json", "rhoconnect-client"]
# extensions: ["json", "another-extension"]
